[tool.ruff.lint]
select = ["B", "E", "F", "I", "W"]

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_missing_imports = true
disable_error_code = "import-untyped"
explicit_package_bases = true
plugins = "numpy.typing.mypy_plugin"

[tool.pyright]
python_version = "3.10"
